alias up='sudo pacman -Syu'
alias pac='sudo pacman -S '
alias cdscripts='cd ~/.local/share/Scripts'
alias script='cdscripts && '
alias addsearch='script ./dmenu_add_to_search.sh'
alias server='ssh root@192.168.86.126'
alias update='sudo pacman -Syu'
alias fixscreen='script ./screen_config.sh'
alias hi='echo whatsup?'

alias send='websocat ws://localhost:8081'
